### ISSUE TITLE
在“商家”页面刷新，收藏功能的BUG

### ISSUE THREAD

**Issue by chenzeshu** [Kunkka0229/sell#1]
问题描述：链接中加入 `?id=333` 后，点击收藏，收藏变为已收藏，在商家页面刷新，**收藏功能**仍旧显示为false

1.  情况一、不添加keep-alive
按照源码，收藏商家后，在商家页面刷新，商家“未收藏”（`this.favorite = false`）
切其他组件切回，相当于重新请求数据，显示已收藏

2. 情况二、在<rouer-view>添加了`keep-alive`
因为状态直接缓存到内存，这次切其他组件切回来，数据是内存的false数据，导致收藏永久是未收藏了。

**小结**：这个BUG相当于，在商家页面刷新的话，收藏功能失效了

提问：请问如何进行优化较好，思路是否是使this.favorite的获取优于DOM渲染？

**Comment by Kunkka0229** [comment]
我测试了一下没有出现你说的bug，你看一下你点击收藏之后 浏览器 Local Stroage 里是不是添加上了数据，数据是否正确，按说只要添加上了数据就应该不会有问题的

**Comment by chenzeshu** [comment]
Sorry,是我的错。
我错在App.vue下的created(){}中没有注释掉this.seller = response.data
